version: '3'
services:
  server:
    build: ./cmd/server
    ports:
      - "8080:8080"
      - "9090:9090"
      - "5432:5432"
  client-grpc:
    build: ./cmd/client-grpc
    network_mode: host
    ports:
      - "9090:9090"
  client-rest:
    build: ./cmd/client-rest
    network_mode: host
    ports:
      - "8080:8080"
  database:
    image: "postgres:alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
