create table if not exists training
(
    id        bigint generated by default as identity primary key,
    name      varchar(255) not null,
    surname   varchar(255) not null,
    email     varchar(255) not null,
    hasAttend boolean,
    score     int
);